// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heawuwxajoduoqumycxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlYXd1d3hham9kdW9xdW15Y3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0Mzc2NjIsImV4cCI6MjA2MzAxMzY2Mn0.UDxTA2VCkqK8JB7_6vJ8DWKY7hdAegPiZdpiSRwDsKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);